In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [12]:
import lars
from lars import apache

In [15]:
import io
from lars import iis, csv
from lars import apache

with io.open('data/access.log', 'r') as f, \
         io.open('data/output_log.csv', 'wb') as outfile:
    with apache.ApacheSource(f) as source, csv.CSVTarget(outfile) as target:
        for row in source:
            target.write(row)

C:\Users\alexe\anaconda3\lib\site-packages\lars\apache.py:741: ApacheWarning: Line 35063: Line contains invalid data
  warnings.warn(
C:\Users\alexe\anaconda3\lib\site-packages\lars\apache.py:741: ApacheWarning: Line 37502: Line contains invalid data
  warnings.warn(
C:\Users\alexe\anaconda3\lib\site-packages\lars\apache.py:741: ApacheWarning: Line 41260: Line contains invalid data
  warnings.warn(
C:\Users\alexe\anaconda3\lib\site-packages\lars\apache.py:741: ApacheWarning: Line 47987: Line contains invalid data
  warnings.warn(
C:\Users\alexe\anaconda3\lib\site-packages\lars\apache.py:741: ApacheWarning: Line 48114: Line contains invalid data
  warnings.warn(
C:\Users\alexe\anaconda3\lib\site-packages\lars\apache.py:741: ApacheWarning: Line 68813: Line contains invalid data
  warnings.warn(
C:\Users\alexe\anaconda3\lib\site-packages\lars\apache.py:741: ApacheWarning: Line 71617: Line contains invalid data
  warnings.warn(
C:\Users\alexe\anaconda3\lib\site-packages\lars\apache.py:741: ApacheWarning: Line 78898: Line contains invalid data
  warnings.warn(
C:\Users\alexe\anaconda3\lib\site-packages\lars\apache.py:741: ApacheWarning: Line 83054: Line contains invalid data
  warnings.warn(
C:\Users\alexe\anaconda3\lib\site-packages\lars\apache.py:741: ApacheWarning: Line 84091: Line contains invalid data
  warnings.warn(
C:\Users\alexe\anaconda3\lib\site-packages\lars\apache.py:741: ApacheWarning: Line 85642: Line contains invalid data
  warnings.warn(

In [20]:
df_log = pd.read_csv('data/output_log.csv')
df_log.sample(4)
# df_log.describe
#   7 columns: id IP NaN NaN date_time get 200

,81.17.18.60,Unnamed: 1,Unnamed: 2,2022-03-03 21:05:07,GET /press-center/ourNews/ourNews.rss HTTP/1.0,200,43924
91939,36.133.17.81,NaN,NaN,2022-03-04 09:04:26,GET /search/?search_query=%D0%BF%D1%83%D1%82%D...,503,60.0
23644,199.249.230.87,NaN,NaN,2022-03-04 00:51:49,GET /search/?search_query=%D0%BF%D1%83%D1%82%D...,503,60.0
27904,122.226.224.166,NaN,NaN,2022-03-04 00:55:43,GET /search/?search_query=%D0%BF%D1%83%D1%82%D...,200,66888.0
93948,67.207.82.254,NaN,NaN,2022-03-04 09:06:47,GET /search/?search_query=%D0%BF%D1%83%D1%82%D...,503,60.0

In [21]:
df_log.columns = ['IP','UN1','UN2','date_time','request','SA','UN3']
df_log.sample(6)

,IP,UN1,UN2,date_time,request,SA,UN3
66755,51.222.12.245,NaN,NaN,2022-03-04 05:42:39,GET /search/?search_query=%D0%BF%D1%83%D1%82%D...,503,60.0
52799,220.171.121.3,NaN,NaN,2022-03-04 03:57:08,GET /search/?search_query=%D0%BF%D1%83%D1%82%D...,503,60.0
50925,39.183.153.31,NaN,NaN,2022-03-04 03:41:17,GET /search/?search_query=%D0%BF%D1%83%D1%82%D...,503,60.0
67550,111.121.97.110,NaN,NaN,2022-03-04 05:48:15,GET /search/?search_query=%D0%BF%D1%83%D1%82%D...,503,60.0
67767,138.197.88.158,NaN,NaN,2022-03-04 05:49:44,GET /search/?search_query=%D0%BF%D1%83%D1%82%D...,503,60.0
42660,218.89.4.27,NaN,NaN,2022-03-04 02:44:15,GET /search/?search_query=%D0%BF%D1%83%D1%82%D...,503,60.0

In [22]:
df_log.shape

(106905, 7)

In [24]:
df_log.describe()
df_log.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106905 entries, 0 to 106904
Data columns (total 7 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   IP         106905 non-null  object
 1   UN1        7 non-null       object
 2   UN2        0 non-null       float64
 3   date_time  106905 non-null  object
 4   request    106905 non-null  object
 5   SA         106905 non-null  int64
 6   UN3        106480 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 5.7+ MB

In [27]:
df_log['IP'].unique

<bound method Series.unique of 0          87.250.224.8
1           78.46.72.12
2          157.55.39.48
3         5.255.253.189
4          87.250.224.8
              ...
106900    67.207.82.254
106901     42.228.3.158
106902     50.73.45.153
106903    120.211.11.66
106904    94.177.136.34
Name: IP, Length: 106905, dtype: object>

In [28]:
# get distinct values of the dataframe based on column
df_unique = df_log.drop_duplicates(subset = ["IP"])
df_unique.head()

,IP,UN1,UN2,date_time,request,SA,UN3
0,87.250.224.8,NaN,NaN,2022-03-03 21:05:22,GET / HTTP/1.0,200,100284.0
1,78.46.72.12,NaN,NaN,2022-03-03 21:05:25,GET / HTTP/1.0,200,100300.0
2,157.55.39.48,NaN,NaN,2022-03-03 21:05:40,GET /press-center/announces/?curPos=680&cur_cc...,200,75594.0
3,5.255.253.189,NaN,NaN,2022-03-03 21:05:45,GET /press-center/ourNews/ourNews_7250.html HT...,200,59927.0
5,5.255.253.175,NaN,NaN,2022-03-03 21:05:48,GET /assets/js/jquery.dcjqaccordion.2.6.min.js...,200,1106.0

In [29]:
df_log['IP'].value_counts()

178.210.87.251    7980
36.133.183.241     557
45.154.255.147     379
36.133.214.97      369
36.133.17.81       357
                  ...
195.123.245.73       1
202.29.226.54        1
27.147.155.70        1
70.185.68.155        1
120.211.11.66        1
Name: IP, Length: 7164, dtype: int64

In [30]:
df_log[['request']].value_counts()

request
OPTIONS None HTTP/1.0                                                               243
GET / HTTP/1.0                                                                      171
GET /press-center/ourNews/ourNews.rss HTTP/1.0                                      164
GET /assets/js/bootstrap.min.js HTTP/1.1                                            110
GET /assets/js/jquery-3.1.1.min.js HTTP/1.1                                         107
                                                                                   ...
GET /search/?search_query=%D0%BF%D1%83%D1%82%D0%B8%D0%BD&param_35=6451 HTTP/1.0       1
GET /search/?search_query=%D0%BF%D1%83%D1%82%D0%B8%D0%BD&param_35=64437 HTTP/1.0      1
GET /search/?search_query=%D0%BF%D1%83%D1%82%D0%B8%D0%BD&param_35=62580 HTTP/1.0      1
GET /search/?search_query=%D0%BF%D1%83%D1%82%D0%B8%D0%BD&param_35=60930 HTTP/1.0      1
GET /search/?search_query=%D0%BF%D1%83%D1%82%D0%B8%D0%BD&param_52=17635 HTTP/1.0      1
Length: 102952, dtype: int64

In [ ]:
df_log[]

In [ ]:
# df = df.rename(columns={'%>s': 'Status', '%b':'Bytes Returned', 
#                         '%h':'IP', '%l':'Username', '%r': 'Request', '%t': 'Time', '%u': 'Userid', '%{Referer}i': 'Referer', '%{User-Agent}i': 'Agent'})
# df.index = pd.to_datetime(df.pop('Time'))
# test = df.groupby(['IP', 'Agent']).size()
# test.sort()
# print(test[-20:])

In [17]:
# file = open('data/log.txt')
# lines = file.readlines()

# logs = pd.DataFrame(columns=['ip', 'indentd', 'userid', 'time', 'request', 'status', 'size', 'Referer', 'User_agent'])

# regc = re.compile('(?P<ip>.*?) - - \[(?P<time>.*?)\] "(?P<request>.*?)" (?P<status>\d+) (?P<size>\d+) (?P<Referer>.*?) (?P<User_agent>.*?)')

# for line in lines:
#     m = regc.match(line)
#     print(m)
#     ip = m.group('ip')
# #     identd = m.group('identd')
# #     userid = m.group('userid')
# #     time = m.group('time')
#     request = m.group('request')
#     status = m.group('status')
#     size = m.group('size')
#     Referer = m.group('Referer')
#     User_agent = m.group('User_agent')
# #     logs.append([ip, identd, userid, time, request, status, size, Referer, User_agent])
#     logs.append([ip, request, status, size, Referer, User_agent])

# # logs
# print(logs.head())